name: Build Unit Tests

on: push

jobs:
  build:
    runs-on: windows-latest # Required for py_dss_interface as OpenDSS is Windows-only
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with unittest
      run: |
        python -m unittest discover -s ./tests